# Leavetimes

In [1]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [40]:
Sample_leavetimes_df = pd.read_csv("rt_leavetimes_DB_2018.txt", ";", nrows=1000000)
Sample_leavetimes_df

,DATASOURCE,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID,PASSENGERS,PASSENGERSIN,PASSENGERSOUT,DISTANCE,SUPPRESSED,JUSTIFICATIONID,LASTUPDATE,NOTE
0,DB,01-JAN-18 00:00:00,5972116,12,119,48030,48030,48012,48012,2693211,NaN,NaN,NaN,NaN,NaN,NaN,08-JAN-18 17:21:10,NaN
1,DB,01-JAN-18 00:00:00,5966674,12,119,54001,54001,54023,54023,2693267,NaN,NaN,NaN,NaN,NaN,NaN,08-JAN-18 17:21:10,NaN
2,DB,01-JAN-18 00:00:00,5959105,12,119,60001,60001,59955,59955,2693263,NaN,NaN,NaN,NaN,NaN,NaN,08-JAN-18 17:21:10,NaN
3,DB,01-JAN-18 00:00:00,5966888,12,119,58801,58801,58771,58771,2693284,NaN,NaN,NaN,NaN,NaN,NaN,08-JAN-18 17:21:10,NaN
4,DB,01-JAN-18 00:00:00,5965960,12,119,56401,56401,56309,56323,2693209,NaN,NaN,NaN,NaN,NaN,NaN,08-JAN-18 17:21:10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DB,04-JAN-18 00:00:00,5969454,90,2355,75325,75325,75425,75425,2172254,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN
999996,DB,04-JAN-18 00:00:00,5963350,90,2355,73525,73525,73576,73576,2172296,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN
999997,DB,04-JAN-18 00:00:00,5960994,90,2355,74725,74725,74954,74954,1932364,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN
999998,DB,04-JAN-18 00:00:00,5972429,90,2355,72325,72325,71965,71965,1932328,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN
999999,DB,04-JAN-18 00:00:00,5968647,44,201,65914,65914,66426,66449,2406906,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN

In [11]:
suppressed = Sample_leavetimes_df[Sample_leavetimes_df['SUPPRESSED']==1]
print('number of suppressed rows:',suppressed.shape[0])

number of suppressed rows: 514

In [41]:
Sample_leavetimes_df[(Sample_leavetimes_df['SUPPRESSED']==1)]

,DATASOURCE,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID,PASSENGERS,PASSENGERSIN,PASSENGERSOUT,DISTANCE,SUPPRESSED,JUSTIFICATIONID,LASTUPDATE,NOTE
6968,DB,01-JAN-18 00:00:00,5958112,29,19,55561,55561,55598,55626,2868353,NaN,NaN,NaN,NaN,1.0,4.849814e+17,08-JAN-18 17:21:10,NaN
10804,DB,01-JAN-18 00:00:00,5970418,1,2492,64200,64200,63857,63857,2534871,NaN,NaN,NaN,NaN,1.0,4.849814e+17,08-JAN-18 17:21:10,NaN
17600,DB,01-JAN-18 00:00:00,5971326,2,493,53326,53326,53325,53325,1000897,NaN,NaN,NaN,NaN,1.0,4.849814e+17,08-JAN-18 17:21:10,NaN
17623,DB,01-JAN-18 00:00:00,5971326,3,494,53408,53408,53350,53424,1000897,NaN,NaN,NaN,NaN,1.0,4.849814e+17,08-JAN-18 17:21:10,NaN
38357,DB,01-JAN-18 00:00:00,5961772,12,4958,79569,79569,79923,79923,2868390,NaN,NaN,NaN,NaN,1.0,4.849814e+17,08-JAN-18 17:21:10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996269,DB,04-JAN-18 00:00:00,5960263,39,1282,72008,72008,72730,72839,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
997365,DB,04-JAN-18 00:00:00,5960263,40,4456,72120,72120,72962,72995,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
998483,DB,04-JAN-18 00:00:00,5960263,41,1284,72184,72184,73037,73148,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
999654,DB,04-JAN-18 00:00:00,5960263,43,1287,72502,72502,73423,73439,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
999960,DB,04-JAN-18 00:00:00,5957322,90,2355,63228,63228,63473,63473,2406900,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN

In [37]:
# examining supprressed rows in sample dataset
# Sample_leavetimes_df[(Sample_leavetimes_df['TRIPID']==5960263)]
# Sample_leavetimes_df[(Sample_leavetimes_df['TRIPID']==5960263) & (Sample_leavetimes_df['DAYOFSERVICE']=='03-JAN-18 00:00:00')].sort_values(["PROGRNUMBER"], ascending=True).head(50)

,DATASOURCE,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID,PASSENGERS,PASSENGERSIN,PASSENGERSOUT,DISTANCE,SUPPRESSED,JUSTIFICATIONID,LASTUPDATE,NOTE
421959,DB,02-JAN-18 00:00:00,5960263,76,2975,74216,74216,74968,74968,1000957,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-18 20:18:05,NaN
421962,DB,02-JAN-18 00:00:00,5960263,75,5052,74165,74165,73803,73811,1000957,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-18 20:18:05,NaN
421966,DB,02-JAN-18 00:00:00,5960263,74,5051,74127,74127,73757,73768,1000957,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-18 20:18:05,NaN
421970,DB,02-JAN-18 00:00:00,5960263,73,2971,74046,74046,73696,73696,1000957,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-18 20:18:05,NaN
421974,DB,02-JAN-18 00:00:00,5960263,72,2970,73991,73991,73674,73674,1000957,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-18 20:18:05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991836,DB,04-JAN-18 00:00:00,5960263,33,51,71008,71008,70702,70712,1000238,NaN,NaN,NaN,NaN,NaN,NaN,11-JAN-18 18:55:15,NaN
996269,DB,04-JAN-18 00:00:00,5960263,39,1282,72008,72008,72730,72839,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
997365,DB,04-JAN-18 00:00:00,5960263,40,4456,72120,72120,72962,72995,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
998483,DB,04-JAN-18 00:00:00,5960263,41,1284,72184,72184,73037,73148,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN
999654,DB,04-JAN-18 00:00:00,5960263,43,1287,72502,72502,73423,73439,1000238,NaN,NaN,NaN,NaN,1.0,4.849814e+17,11-JAN-18 18:55:15,NaN

Due to the size of the leavetimes file, we will have to read it in chunks and examine each chunk individually.

In [3]:
chunk_count = 1
for chunk in pd.read_csv("rt_leavetimes_DB_2018.txt", ";", chunksize=1000000):
    print("Chunk:",chunk_count)
    print('Duplicate Rows:', chunk.duplicated().sum())
    suppressed = chunk[chunk['SUPPRESSED']==1]
    print('number of suppressed rows',suppressed.shape[0])
    columns = list(Sample_leavetimes_df.columns.values)
    for column in columns:
        print("{} null values:".format(column),chunk[column].isnull().sum())
    print("--------------------")
    chunk_count+=1

Chunk: 1
Duplicate Rows: 0
number of suppressed rows 514
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996979
JUSTIFICATIONID null values: 996979
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 2
Duplicate Rows: 0
number of suppressed rows 556
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997667
JUSTIFICATIONID null values: 997667
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 3
Duplicate Rows: 0
number of suppressed rows 798
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 998583
JUSTIFICATIONID null values: 998583
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 4
Duplicate Rows: 0
number of suppressed rows 805
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997942
JUSTIFICATIONID null values: 997942
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 5
Duplicate Rows: 0
number of suppressed rows 1090
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997585
JUSTIFICATIONID null values: 997585
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 6
Duplicate Rows: 0
number of suppressed rows 755
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 998075
JUSTIFICATIONID null values: 998075
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 7
Duplicate Rows: 0
number of suppressed rows 1027
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997122
JUSTIFICATIONID null values: 997122
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 8
Duplicate Rows: 0
number of suppressed rows 1117
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996931
JUSTIFICATIONID null values: 996931
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 9
Duplicate Rows: 0
number of suppressed rows 1068
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997533
JUSTIFICATIONID null values: 997533
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 10
Duplicate Rows: 0
number of suppressed rows 809
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997934
JUSTIFICATIONID null values: 997934
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 11
Duplicate Rows: 0
number of suppressed rows 880
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997706
JUSTIFICATIONID null values: 997706
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 12
Duplicate Rows: 0
number of suppressed rows 761
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996808
JUSTIFICATIONID null values: 996808
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 13
Duplicate Rows: 0
number of suppressed rows 882
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997004
JUSTIFICATIONID null values: 997004
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 14
Duplicate Rows: 0
number of suppressed rows 984
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997414
JUSTIFICATIONID null values: 997414
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 15
Duplicate Rows: 0
number of suppressed rows 936
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996938
JUSTIFICATIONID null values: 996938
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 16
Duplicate Rows: 0
number of suppressed rows 746
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 998363
JUSTIFICATIONID null values: 998363
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 17
Duplicate Rows: 0
number of suppressed rows 1200
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997418
JUSTIFICATIONID null values: 997418
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 18
Duplicate Rows: 0
number of suppressed rows 837
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997551
JUSTIFICATIONID null values: 997551
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 19
Duplicate Rows: 0
number of suppressed rows 2377
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993129
JUSTIFICATIONID null values: 993129
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 20
Duplicate Rows: 0
number of suppressed rows 908
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995648
JUSTIFICATIONID null values: 995648
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 21
Duplicate Rows: 0
number of suppressed rows 1628
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994077
JUSTIFICATIONID null values: 994077
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 22
Duplicate Rows: 0
number of suppressed rows 1428
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994505
JUSTIFICATIONID null values: 994505
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 23
Duplicate Rows: 0
number of suppressed rows 1105
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997132
JUSTIFICATIONID null values: 997132
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 24
Duplicate Rows: 0
number of suppressed rows 1964
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995494
JUSTIFICATIONID null values: 995494
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 25
Duplicate Rows: 0
number of suppressed rows 1847
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995586
JUSTIFICATIONID null values: 995586
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 26
Duplicate Rows: 0
number of suppressed rows 1200
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997055
JUSTIFICATIONID null values: 997055
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 27
Duplicate Rows: 0
number of suppressed rows 855
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997987
JUSTIFICATIONID null values: 997987
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 28
Duplicate Rows: 0
number of suppressed rows 789
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996631
JUSTIFICATIONID null values: 996631
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 29
Duplicate Rows: 0
number of suppressed rows 929
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996244
JUSTIFICATIONID null values: 996244
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 30
Duplicate Rows: 0
number of suppressed rows 607
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997644
JUSTIFICATIONID null values: 997644
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 31
Duplicate Rows: 0
number of suppressed rows 766
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995328
JUSTIFICATIONID null values: 995328
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 32
Duplicate Rows: 0
number of suppressed rows 983
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996305
JUSTIFICATIONID null values: 996305
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 33
Duplicate Rows: 0
number of suppressed rows 1231
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996227
JUSTIFICATIONID null values: 996227
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 34
Duplicate Rows: 0
number of suppressed rows 766
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996509
JUSTIFICATIONID null values: 996509
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 35
Duplicate Rows: 0
number of suppressed rows 626
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997620
JUSTIFICATIONID null values: 997620
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 36
Duplicate Rows: 0
number of suppressed rows 1120
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997251
JUSTIFICATIONID null values: 997251
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 37
Duplicate Rows: 0
number of suppressed rows 1581
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995668
JUSTIFICATIONID null values: 995668
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 38
Duplicate Rows: 0
number of suppressed rows 1271
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995504
JUSTIFICATIONID null values: 995504
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 39
Duplicate Rows: 0
number of suppressed rows 780
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996450
JUSTIFICATIONID null values: 996450
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 40
Duplicate Rows: 0
number of suppressed rows 975
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994796
JUSTIFICATIONID null values: 994796
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 41
Duplicate Rows: 0
number of suppressed rows 1263
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995926
JUSTIFICATIONID null values: 995926
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 42
Duplicate Rows: 0
number of suppressed rows 1530
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994142
JUSTIFICATIONID null values: 994142
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 43
Duplicate Rows: 0
number of suppressed rows 1214
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995799
JUSTIFICATIONID null values: 995799
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 44
Duplicate Rows: 0
number of suppressed rows 900
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996665
JUSTIFICATIONID null values: 996665
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 45
Duplicate Rows: 0
number of suppressed rows 1285
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997040
JUSTIFICATIONID null values: 997040
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 46
Duplicate Rows: 0
number of suppressed rows 745
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 997047
JUSTIFICATIONID null values: 997047
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 47
Duplicate Rows: 0
number of suppressed rows 1132
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994704
JUSTIFICATIONID null values: 994704
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 48
Duplicate Rows: 0
number of suppressed rows 1483
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995085
JUSTIFICATIONID null values: 995085
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 49
Duplicate Rows: 0
number of suppressed rows 1304
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995214
JUSTIFICATIONID null values: 995214
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 50
Duplicate Rows: 0
number of suppressed rows 1337
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994771
JUSTIFICATIONID null values: 994771
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 51
Duplicate Rows: 0
number of suppressed rows 1526
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996583
JUSTIFICATIONID null values: 996583
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 52
Duplicate Rows: 0
number of suppressed rows 1182
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995491
JUSTIFICATIONID null values: 995491
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 53
Duplicate Rows: 0
number of suppressed rows 1406
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996052
JUSTIFICATIONID null values: 996052
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 54
Duplicate Rows: 0
number of suppressed rows 1180
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995425
JUSTIFICATIONID null values: 995425
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 55
Duplicate Rows: 0
number of suppressed rows 741
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996558
JUSTIFICATIONID null values: 996558
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 56
Duplicate Rows: 0
number of suppressed rows 1086
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993679
JUSTIFICATIONID null values: 993679
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 57
Duplicate Rows: 0
number of suppressed rows 1022
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994443
JUSTIFICATIONID null values: 994443
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 58
Duplicate Rows: 0
number of suppressed rows 1817
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992665
JUSTIFICATIONID null values: 992665
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 59
Duplicate Rows: 0
number of suppressed rows 1258
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994773
JUSTIFICATIONID null values: 994773
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 60
Duplicate Rows: 0
number of suppressed rows 1674
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993074
JUSTIFICATIONID null values: 993074
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 61
Duplicate Rows: 0
number of suppressed rows 1337
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993790
JUSTIFICATIONID null values: 993790
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 62
Duplicate Rows: 0
number of suppressed rows 1222
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992291
JUSTIFICATIONID null values: 992291
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 63
Duplicate Rows: 0
number of suppressed rows 1822
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992078
JUSTIFICATIONID null values: 992078
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 64
Duplicate Rows: 0
number of suppressed rows 1184
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994031
JUSTIFICATIONID null values: 994031
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 65
Duplicate Rows: 0
number of suppressed rows 1241
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994123
JUSTIFICATIONID null values: 994123
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 66
Duplicate Rows: 0
number of suppressed rows 1281
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994476
JUSTIFICATIONID null values: 994476
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 67
Duplicate Rows: 0
number of suppressed rows 1202
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992610
JUSTIFICATIONID null values: 992610
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 68
Duplicate Rows: 0
number of suppressed rows 1463
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993011
JUSTIFICATIONID null values: 993011
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 69
Duplicate Rows: 0
number of suppressed rows 1060
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994290
JUSTIFICATIONID null values: 994290
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 70
Duplicate Rows: 0
number of suppressed rows 1102
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994738
JUSTIFICATIONID null values: 994744
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 71
Duplicate Rows: 0
number of suppressed rows 1167
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992699
JUSTIFICATIONID null values: 992699
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 72
Duplicate Rows: 0
number of suppressed rows 1086
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994357
JUSTIFICATIONID null values: 994357
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 73
Duplicate Rows: 0
number of suppressed rows 1340
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993048
JUSTIFICATIONID null values: 993048
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 74
Duplicate Rows: 0
number of suppressed rows 1332
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995145
JUSTIFICATIONID null values: 995145
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 75
Duplicate Rows: 0
number of suppressed rows 1262
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 991216
JUSTIFICATIONID null values: 991216
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 76
Duplicate Rows: 0
number of suppressed rows 941
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993390
JUSTIFICATIONID null values: 993390
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 77
Duplicate Rows: 0
number of suppressed rows 1119
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993447
JUSTIFICATIONID null values: 993447
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 78
Duplicate Rows: 0
number of suppressed rows 4501
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 989776
JUSTIFICATIONID null values: 989776
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 79
Duplicate Rows: 0
number of suppressed rows 1568
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993150
JUSTIFICATIONID null values: 993151
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 80
Duplicate Rows: 0
number of suppressed rows 1418
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992979
JUSTIFICATIONID null values: 992979
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 81
Duplicate Rows: 0
number of suppressed rows 1486
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 990319
JUSTIFICATIONID null values: 990319
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 82
Duplicate Rows: 0
number of suppressed rows 1303
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992307
JUSTIFICATIONID null values: 992307
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 83
Duplicate Rows: 0
number of suppressed rows 1123
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992979
JUSTIFICATIONID null values: 992979
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 84
Duplicate Rows: 0
number of suppressed rows 1354
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993818
JUSTIFICATIONID null values: 993818
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 85
Duplicate Rows: 0
number of suppressed rows 1921
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993222
JUSTIFICATIONID null values: 993222
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 86
Duplicate Rows: 0
number of suppressed rows 996
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993465
JUSTIFICATIONID null values: 993465
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 87
Duplicate Rows: 0
number of suppressed rows 1612
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 990868
JUSTIFICATIONID null values: 990868
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 88
Duplicate Rows: 0
number of suppressed rows 1209
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 989822
JUSTIFICATIONID null values: 989822
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 89
Duplicate Rows: 0
number of suppressed rows 1162
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993352
JUSTIFICATIONID null values: 993352
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 90
Duplicate Rows: 0
number of suppressed rows 2380
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992572
JUSTIFICATIONID null values: 992572
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 91
Duplicate Rows: 0
number of suppressed rows 1519
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992570
JUSTIFICATIONID null values: 992570
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 92
Duplicate Rows: 0
number of suppressed rows 2622
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993095
JUSTIFICATIONID null values: 993095
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 93
Duplicate Rows: 0
number of suppressed rows 1944
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995700
JUSTIFICATIONID null values: 995700
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 94
Duplicate Rows: 0
number of suppressed rows 1424
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993694
JUSTIFICATIONID null values: 993715
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 95
Duplicate Rows: 0
number of suppressed rows 1077
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995020
JUSTIFICATIONID null values: 995020
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 96
Duplicate Rows: 0
number of suppressed rows 1194
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994559
JUSTIFICATIONID null values: 994559
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 97
Duplicate Rows: 0
number of suppressed rows 1301
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992771
JUSTIFICATIONID null values: 992771
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 98
Duplicate Rows: 0
number of suppressed rows 1451
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994789
JUSTIFICATIONID null values: 994796
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 99
Duplicate Rows: 0
number of suppressed rows 1489
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994844
JUSTIFICATIONID null values: 994845
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 100
Duplicate Rows: 0
number of suppressed rows 1575
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993362
JUSTIFICATIONID null values: 993362
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 101
Duplicate Rows: 0
number of suppressed rows 1623
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994597
JUSTIFICATIONID null values: 994597
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 102
Duplicate Rows: 0
number of suppressed rows 1646
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996104
JUSTIFICATIONID null values: 996104
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 103
Duplicate Rows: 0
number of suppressed rows 1259
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996255
JUSTIFICATIONID null values: 996255
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 104
Duplicate Rows: 0
number of suppressed rows 1619
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993496
JUSTIFICATIONID null values: 993496
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 105
Duplicate Rows: 0
number of suppressed rows 1383
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 992923
JUSTIFICATIONID null values: 992923
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 106
Duplicate Rows: 0
number of suppressed rows 1513
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994159
JUSTIFICATIONID null values: 994159
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 107
Duplicate Rows: 0
number of suppressed rows 1427
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995113
JUSTIFICATIONID null values: 995113
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 108
Duplicate Rows: 0
number of suppressed rows 1454
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993680
JUSTIFICATIONID null values: 993680
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 109
Duplicate Rows: 0
number of suppressed rows 1350
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994110
JUSTIFICATIONID null values: 994110
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 110
Duplicate Rows: 0
number of suppressed rows 1478
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 993148
JUSTIFICATIONID null values: 993148
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 111
Duplicate Rows: 0
number of suppressed rows 1876
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994641
JUSTIFICATIONID null values: 994641
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 112
Duplicate Rows: 0
number of suppressed rows 1568
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995365
JUSTIFICATIONID null values: 995365
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------

Chunk: 113
Duplicate Rows: 0
number of suppressed rows 701
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 996658
JUSTIFICATIONID null values: 996658
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 114
Duplicate Rows: 0
number of suppressed rows 2317
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994385
JUSTIFICATIONID null values: 994385
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 115
Duplicate Rows: 0
number of suppressed rows 1047
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 994797
JUSTIFICATIONID null values: 994820
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 116
Duplicate Rows: 0
number of suppressed rows 1050
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 1000000
PASSENGERSIN null values: 1000000
PASSENGERSOUT null values: 1000000
DISTANCE null values: 1000000
SUPPRESSED null values: 995668
JUSTIFICATIONID null values: 995682
LASTUPDATE null values: 0
NOTE null values: 1000000
--------------------
Chunk: 117
Duplicate Rows: 0
number of suppressed rows 1031
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
PROGRNUMBER null values: 0
STOPPOINTID null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 0
ACTUALTIME_DEP null values: 0
VEHICLEID null values: 0
PASSENGERS null values: 949113
PASSENGERSIN null values: 949113
PASSENGERSOUT null values: 949113
DISTANCE null values: 949113
SUPPRESSED null values: 944102
JUSTIFICATIONID null values: 944102
LASTUPDATE null values: 0
NOTE null values: 949113
--------------------

Based on these results:
- no duplicate rows 
- DATASOURCE will be dropped as it contains constant values and therefore provides no information to our model. 
- we can remove features: PASSENGERS, PASSENGERSIN, PASSENGERSOUT, DISTANCE, NOTE as they contain only null values.
- JUSTIFICATIONID contains primarily null vlaues, this is a fault code and therefore will not be necessary in our model so it will be dropped.
- LASTUPDATE is not relevant to our model as it does not provide any information on when the journey took place.
- There were no duplicate rows in any of the chunks.
- There were a number of rows where suppressed = 1, these will have to be examined and may be dropped. 


- After further examination, it seems that these rows are worth keeping as the journey times that can be retrieved form these rows still provide information to our models. While a large number of rows are suppressed, this indicates that the rows are partially suppressed and not fully suppressed as we can see in the trips data set that there are no trips where suppressed is 1. this data still provides data to our models and therefore will not be dropped.

In [4]:
columns = ['DAYOFSERVICE','TRIPID','PROGRNUMBER','STOPPOINTID','PLANNEDTIME_ARR',
           'PLANNEDTIME_DEP','ACTUALTIME_ARR','ACTUALTIME_DEP','VEHICLEID']

Sample_leavetimes_df = Sample_leavetimes_df[columns]

In [5]:
Sample_leavetimes_df

,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID
0,01-JAN-18 00:00:00,5972116,12,119,48030,48030,48012,48012,2693211
1,01-JAN-18 00:00:00,5966674,12,119,54001,54001,54023,54023,2693267
2,01-JAN-18 00:00:00,5959105,12,119,60001,60001,59955,59955,2693263
3,01-JAN-18 00:00:00,5966888,12,119,58801,58801,58771,58771,2693284
4,01-JAN-18 00:00:00,5965960,12,119,56401,56401,56309,56323,2693209
...,...,...,...,...,...,...,...,...,...
999995,04-JAN-18 00:00:00,5969454,90,2355,75325,75325,75425,75425,2172254
999996,04-JAN-18 00:00:00,5963350,90,2355,73525,73525,73576,73576,2172296
999997,04-JAN-18 00:00:00,5960994,90,2355,74725,74725,74954,74954,1932364
999998,04-JAN-18 00:00:00,5972429,90,2355,72325,72325,71965,71965,1932328
999999,04-JAN-18 00:00:00,5968647,44,201,65914,65914,66426,66449,2406906

In [6]:
Sample_leavetimes_df['DAYOFSERVICE'] = Sample_leavetimes_df['DAYOFSERVICE'].astype('datetime64[ns]')
Sample_leavetimes_df['VEHICLEID'] = Sample_leavetimes_df['VEHICLEID'].astype('category')
Sample_leavetimes_df['PROGRNUMBER'] = Sample_leavetimes_df['PROGRNUMBER'].astype('category')
Sample_leavetimes_df['STOPPOINTID'] = Sample_leavetimes_df['STOPPOINTID'].astype('category')
Sample_leavetimes_df['TRIPID'] = Sample_leavetimes_df['TRIPID'].astype('category')

In [7]:
Sample_leavetimes_df.dtypes

DAYOFSERVICE       datetime64[ns]
TRIPID                   category
PROGRNUMBER              category
STOPPOINTID              category
PLANNEDTIME_ARR             int64
PLANNEDTIME_DEP             int64
ACTUALTIME_ARR              int64
ACTUALTIME_DEP              int64
VEHICLEID                category
dtype: object

In [8]:
Sample_leavetimes_df['MONTH'] = Sample_leavetimes_df['DAYOFSERVICE'].dt.month
Sample_leavetimes_df['DAY'] = Sample_leavetimes_df['DAYOFSERVICE'].dt.dayofweek
Sample_leavetimes_df['QUARTER'] = Sample_leavetimes_df['DAYOFSERVICE'].dt.quarter

In [9]:
#converting the time stamps in seconds to %H:%M:%S timestamps
Sample_leavetimes_df['ARRIVAL_TIME_ACTUAL'] = pd.to_datetime(Sample_leavetimes_df["ACTUALTIME_ARR"], unit='s').dt.strftime("%H:%M:%S") 
Sample_leavetimes_df['DEPARTURE_TIME_ACTUAL'] = pd.to_datetime(Sample_leavetimes_df["ACTUALTIME_DEP"], unit='s').dt.strftime("%H:%M:%S")

In [10]:
Sample_leavetimes_df['DWELL_TIME'] = Sample_leavetimes_df['ACTUALTIME_DEP'] - Sample_leavetimes_df['ACTUALTIME_ARR']

# Trips

In [2]:
Trips_df = pd.read_csv("rt_trips_DB_2018.txt", ";")
Trips_df

,DATASOURCE,DAYOFSERVICE,TRIPID,LINEID,ROUTEID,DIRECTION,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,BASIN,TENDERLOT,SUPPRESSED,JUSTIFICATIONID,LASTUPDATE,NOTE
0,DB,07-FEB-18 00:00:00,6253783,68,68_80,1,87245,84600,87524.0,84600.0,BasDef,NaN,NaN,NaN,28-FEB-18 12:05:11,",2967409,"
1,DB,07-FEB-18 00:00:00,6262138,25B,25B_271,2,30517,26460,32752.0,NaN,BasDef,NaN,NaN,NaN,28-FEB-18 12:05:11,",2580260,"
2,DB,07-FEB-18 00:00:00,6254942,45A,45A_70,2,35512,32100,36329.0,32082.0,BasDef,NaN,NaN,NaN,28-FEB-18 12:05:11,",2448968,"
3,DB,07-FEB-18 00:00:00,6259460,25A,25A_273,1,57261,54420,58463.0,54443.0,BasDef,NaN,NaN,NaN,28-FEB-18 12:05:11,",3094242,"
4,DB,07-FEB-18 00:00:00,6253175,14,14_15,1,85383,81600,84682.0,81608.0,BasDef,NaN,NaN,NaN,28-FEB-18 12:05:11,",2526331,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2182632,DB,14-MAY-18 00:00:00,6765849,123,123_36,2,61560,57840,61365.0,57859.0,BasDef,NaN,NaN,NaN,26-JUN-18 09:13:13,",3216350,"
2182633,DB,14-MAY-18 00:00:00,6765469,75,75_17,1,53416,48600,NaN,48823.0,BasDef,NaN,NaN,NaN,26-JUN-18 09:13:13,",2865284,"
2182634,DB,14-MAY-18 00:00:00,6765486,33D,33D_62,2,29460,26400,29904.0,NaN,BasDef,NaN,NaN,NaN,26-JUN-18 09:13:13,",3077688,"
2182635,DB,14-MAY-18 00:00:00,6764987,70,70_60,1,65277,60600,66341.0,NaN,BasDef,NaN,NaN,NaN,26-JUN-18 09:13:13,",3208841,"
2182636,DB,14-MAY-18 00:00:00,6765012,27,27_19,1,47722,41700,47508.0,41642.0,BasDef,NaN,NaN,NaN,26-JUN-18 09:13:13,",2960092,"

In [5]:
print('Duplicate Rows:', Trips_df.duplicated().sum())

Duplicate Rows: 0

In [6]:
suppressed = Trips_df[Trips_df['SUPPRESSED']==0]
print('number of suppressed rows:',suppressed.shape[0])

number of suppressed rows: 4333

In [8]:
suppressed = Trips_df[Trips_df['SUPPRESSED']==1]
print('number of suppressed rows:',suppressed.shape[0])

number of suppressed rows: 0

In [45]:
suppressed = Trips_df[Trips_df['SUPPRESSED'].isnull()]
print('number of suppressed rows:',suppressed.shape[0])

number of suppressed rows: 2178304

according to the concept design extract for this data "if the trips is partially suppressed the flag “Suppressed” will not be check", the large majority of the rows in the trips dataset are not checked and this therefore indicates that a large majority of the trips were partially supprressed. It is for this reason that the rows where suppressed=1 were not dropped from the leavetimes dataset.

Dataframe contains no duplicate rows or rows where suppressed=1

In [15]:
columns = list(Trips_df.columns.values)
print("--------------------")
for column in columns:
    print("{} null values:".format(column),Trips_df[column].isnull().sum())
print("--------------------")

--------------------
DATASOURCE null values: 0
DAYOFSERVICE null values: 0
TRIPID null values: 0
LINEID null values: 0
ROUTEID null values: 0
DIRECTION null values: 0
PLANNEDTIME_ARR null values: 0
PLANNEDTIME_DEP null values: 0
ACTUALTIME_ARR null values: 137207
ACTUALTIME_DEP null values: 164551
BASIN null values: 0
TENDERLOT null values: 2182637
SUPPRESSED null values: 2178304
JUSTIFICATIONID null values: 2178307
LASTUPDATE null values: 0
NOTE null values: 0
--------------------

In [4]:
columns = ['DAYOFSERVICE','TRIPID','LINEID','ROUTEID','DIRECTION']
Trips_df = Trips_df[columns]

In [5]:
Trips_df.dtypes

DAYOFSERVICE    object
TRIPID           int64
LINEID          object
ROUTEID         object
DIRECTION        int64
dtype: object

In [6]:
Trips_df['DAYOFSERVICE'] = Trips_df['DAYOFSERVICE'].astype('datetime64[ns]')

In [7]:
Trips_df.dtypes

DAYOFSERVICE    datetime64[ns]
TRIPID                   int64
LINEID                  object
ROUTEID                 object
DIRECTION                int64
dtype: object

In [20]:
Trips_df['LINEID'].value_counts()

46A    76728
145    62730
15     58083
40     56974
39A    55301
       ...
68X      243
51X      238
16D       84
41D       36
33E       14
Name: LINEID, Length: 130, dtype: int64

# Merging leavetimes and Trips

In [30]:
Merged_DF = pd.merge(Sample_leavetimes_df, Trips_df[['DAYOFSERVICE','TRIPID','LINEID','ROUTEID','DIRECTION']],
                    on = ['TRIPID','DAYOFSERVICE'])
Merged_DF.head()

,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID,MONTH,DAY,Quarter,ARRIVAL_TIME_ACTUAL,DEPARTURE_TIME_ACTUAL,DWELL_TIME,LINEID,ROUTEID,DIRECTION
0,2018-01-01,5972116,12,119,48030,48030,48012,48012,2693211,1,0,1,13:20:12,13:20:12,0,1,1_37,1
1,2018-01-01,5972116,13,44,48079,48079,48058,48058,2693211,1,0,1,13:20:58,13:20:58,0,1,1_37,1
2,2018-01-01,5972116,14,7603,48114,48114,48071,48071,2693211,1,0,1,13:21:11,13:21:11,0,1,1_37,1
3,2018-01-01,5972116,15,45,48155,48155,48089,48100,2693211,1,0,1,13:21:29,13:21:40,11,1,1_37,1
4,2018-01-01,5972116,16,46,48221,48221,48137,48137,2693211,1,0,1,13:22:17,13:22:17,0,1,1_37,1

In [73]:
Merged_DF['LINEID'].value_counts()

27     35124
13     34031
46A    32683
15     32388
40     31868
       ...
33D        0
40E        0
16D        0
33E        0
41D        0
Name: LINEID, Length: 130, dtype: int64


Now that we have successfully performed these transforamtions on the leavetimes sample dataframe and trips dataframe, we will move on to performing this process on the full leavetimes dataframe in a series of chunks. Each transformed chunk will then be appended to a new cleaned CSV file.

# Cleaning the leavetimes dataframe, merging with Trips dataframe, splitting by route and appending it to a new CSV.


This cell takes roughly 30 mins to run. Do not run as it will overwrite the cleaned master dataframe.

In [26]:
columns = ['DAYOFSERVICE','TRIPID','PROGRNUMBER','STOPPOINTID','PLANNEDTIME_ARR',
           'PLANNEDTIME_DEP','ACTUALTIME_ARR','ACTUALTIME_DEP','VEHICLEID']
chunk_count = 1
for chunk in pd.read_csv("rt_leavetimes_DB_2018.txt", ";", usecols=columns , chunksize=5000000):
    print("Chunk:",chunk_count)
    
    #convert datatypes
    chunk['DAYOFSERVICE'] = chunk['DAYOFSERVICE'].astype('datetime64[ns]')
    chunk['TRIPID'] = chunk['TRIPID'].astype('int')
    chunk['PROGRNUMBER'] = chunk['PROGRNUMBER'].astype('int')
    chunk['STOPPOINTID'] = chunk['STOPPOINTID'].astype('int')
    chunk['PLANNEDTIME_ARR'] = chunk['PLANNEDTIME_ARR'].astype('int')
    chunk['PLANNEDTIME_DEP'] = chunk['PLANNEDTIME_DEP'].astype('int')
    chunk['ACTUALTIME_ARR'] = chunk['ACTUALTIME_ARR'].astype('int')
    chunk['ACTUALTIME_DEP'] = chunk['ACTUALTIME_DEP'].astype('int')
    chunk['VEHICLEID'] = chunk['VEHICLEID'].astype('int')
    
    
#     #remove rows where suppressed is one 
#     chunk = chunk[chunk.suppressed != 1]
    
    #create features
    chunk['MONTH'] = chunk['DAYOFSERVICE'].dt.month
    chunk['DAY'] = chunk['DAYOFSERVICE'].dt.dayofweek
    chunk['Quarter'] = chunk['DAYOFSERVICE'].dt.quarter
    chunk['ARRIVAL_TIME_ACTUAL'] = pd.to_datetime(chunk["ACTUALTIME_ARR"], unit='s').dt.strftime("%H:%M:%S") 
    chunk['DEPARTURE_TIME_ACTUAL'] = pd.to_datetime(chunk["ACTUALTIME_DEP"], unit='s').dt.strftime("%H:%M:%S")
    chunk['DWELL_TIME'] = chunk['ACTUALTIME_DEP'] - chunk['ACTUALTIME_ARR']
    
    #merge dataframes together 
    chunk = pd.merge(chunk, Trips_df[['DAYOFSERVICE','TRIPID','LINEID','ROUTEID','DIRECTION']],
            on = ['TRIPID','DAYOFSERVICE'])    
    
    #append dataframe to new csv
    chunk.to_csv('Clean_Master_Dataset_copy.csv', index=False, header=True , mode='a') 

    print("Chunk",chunk_count, "Status: Complete")
    print("--------------------")
    chunk_count+=1

Chunk: 1
Chunk 1 Status: Complete
--------------------
Chunk: 2
Chunk 2 Status: Complete
--------------------
Chunk: 3
Chunk 3 Status: Complete
--------------------
Chunk: 4
Chunk 4 Status: Complete
--------------------
Chunk: 5
Chunk 5 Status: Complete
--------------------
Chunk: 6
Chunk 6 Status: Complete
--------------------
Chunk: 7
Chunk 7 Status: Complete
--------------------
Chunk: 8
Chunk 8 Status: Complete
--------------------
Chunk: 9
Chunk 9 Status: Complete
--------------------
Chunk: 10
Chunk 10 Status: Complete
--------------------
Chunk: 11
Chunk 11 Status: Complete
--------------------
Chunk: 12
Chunk 12 Status: Complete
--------------------
Chunk: 13
Chunk 13 Status: Complete
--------------------
Chunk: 14
Chunk 14 Status: Complete
--------------------
Chunk: 15
Chunk 15 Status: Complete
--------------------
Chunk: 16
Chunk 16 Status: Complete
--------------------
Chunk: 17
Chunk 17 Status: Complete
--------------------
Chunk: 18
Chunk 18 Status: Complete
--------------------
Chunk: 19
Chunk 19 Status: Complete
--------------------
Chunk: 20
Chunk 20 Status: Complete
--------------------
Chunk: 21
Chunk 21 Status: Complete
--------------------
Chunk: 22
Chunk 22 Status: Complete
--------------------
Chunk: 23
Chunk 23 Status: Complete
--------------------
Chunk: 24
Chunk 24 Status: Complete
--------------------

# Function to split up the dataframe by routes

In [ ]:
Clean_Master_Dataset.csv

In [40]:
def Route_splitter(dataframe):
    routes = Trips_df.LINEID.unique()
    for route in routes:
        route_df = dataframe.loc[dataframe['LINEID']== route]
        route_df.to_csv("Cleaned_By_Route/route_{}.csv".format(route), index=False, header=None , mode='a')
    return route_df

In [41]:
chunk_count = 1
for chunk in pd.read_csv("Clean_Master_Dataset.csv", chunksize=5000000, low_memory=False):
    print("Chunk:",chunk_count)
    Route_splitter(chunk)
    print("Chunk",chunk_count, "Status: Complete")
    print("--------------------")
    chunk_count+=1

Chunk: 1
Chunk 1 Status: Complete
--------------------
Chunk: 2
Chunk 2 Status: Complete
--------------------
Chunk: 3
Chunk 3 Status: Complete
--------------------
Chunk: 4
Chunk 4 Status: Complete
--------------------
Chunk: 5
Chunk 5 Status: Complete
--------------------
Chunk: 6
Chunk 6 Status: Complete
--------------------
Chunk: 7
Chunk 7 Status: Complete
--------------------
Chunk: 8
Chunk 8 Status: Complete
--------------------
Chunk: 9
Chunk 9 Status: Complete
--------------------
Chunk: 10
Chunk 10 Status: Complete
--------------------
Chunk: 11
Chunk 11 Status: Complete
--------------------
Chunk: 12
Chunk 12 Status: Complete
--------------------
Chunk: 13
Chunk 13 Status: Complete
--------------------
Chunk: 14
Chunk 14 Status: Complete
--------------------
Chunk: 15
Chunk 15 Status: Complete
--------------------
Chunk: 16
Chunk 16 Status: Complete
--------------------
Chunk: 17
Chunk 17 Status: Complete
--------------------
Chunk: 18
Chunk 18 Status: Complete
--------------------
Chunk: 19
Chunk 19 Status: Complete
--------------------
Chunk: 20
Chunk 20 Status: Complete
--------------------
Chunk: 21
Chunk 21 Status: Complete
--------------------
Chunk: 22
Chunk 22 Status: Complete
--------------------
Chunk: 23
Chunk 23 Status: Complete
--------------------
Chunk: 24
Chunk 24 Status: Complete
--------------------

In [9]:
#this cell adds a header to each of the dataframe that have been split up by route.
headers = ['DAYOFSERVICE','TRIPID', 'PROGRNUMBER', 'STOPPOINTID',
         'PLANNEDTIME_ARR', 'PLANNEDTIME_DEP', 'ACTUALTIME_ARR', 'ACTUALTIME_DEP',
        'VEHICLEID', 'MONTH', 'DAY', 'Quarter', 'ARRIVAL_TIME_ACTUAL',
        'DEPARTURE_TIME_ACTUAL', 'DWELL_TIME', 'LINEID', 'ROUTEID', 'DIRECTION']

routes = Trips_df.LINEID.unique()
for route in routes:
    route_file = pd.read_csv("Cleaned_By_Route/route_{}.csv".format(route),header=None)
    route_file.to_csv("Cleaned_By_Route_Header/route_{}.csv".format(route),header=headers, index=False)