In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
Lin_Reg = pd.read_csv("~/data/Model_Testing/Linear_Regression_Results_direction_split.csv")

In [3]:
Dec_tree = pd.read_csv("~/data/Model_Testing/Decision_Tree_Results.csv")
Dec_tree = Dec_tree.drop([Dec_tree.index[64]])
Dec_tree = Dec_tree.drop([Dec_tree.index[124]])

In [4]:
Random_Forest = pd.read_csv("~/data/Model_Testing/Random_Forest_Results_2.csv")
Random_Forest = Random_Forest.drop([Dec_tree.index[116]])
Random_Forest = Random_Forest.drop([Dec_tree.index[119]])

# Linear Regression

In [5]:
Lin_Reg

,Route,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
0,68,1,10.675,10.646,-0.098,0.267,296.858,17.230,0.747
1,68,2,12.086,12.056,-0.111,0.294,403.423,20.085,0.643
2,25B,1,14.687,14.678,-0.090,0.258,498.301,22.323,0.780
3,25B,2,17.200,17.125,-0.104,0.307,716.524,26.768,0.654
4,45A,1,10.507,10.556,-0.071,0.229,259.242,16.101,0.723
...,...,...,...,...,...,...,...,...,...
247,77X,2,16.594,16.806,-0.117,0.273,760.334,27.574,0.776
248,16D,1,18.307,1709833030.097,-17627144.585,17627144.785,5244810893665171931136.000,72421066642.692,-2517501282304750080.000
249,33E,1,10.043,11.603,-0.104,0.262,339.696,18.431,0.568
250,41D,1,15.572,30533931171.529,213727605.975,213727606.406,90901292795533310558208.000,301498412592.062,-73007332804014751744.000
251,41D,2,15.438,17.585,-0.112,0.331,651.144,25.518,0.774

In [6]:
problematic = Lin_Reg[Lin_Reg['Mean_Absolute_Error_Test']> 1000]

In [7]:
problematic

,Route,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
7,25A,2,15.601,5652562.072,-36234.376,36234.576,5001462009433228288.000,2236394868.853,-3008540712586420.500
29,46A,2,16.206,832259.987,3650.048,3650.544,436791679024969216.000,660902170.540,-279795307406519.000
42,41,1,15.136,1199505.592,11759.582,11760.037,329543314179469184.000,574058633.050,-273416628306184.812
134,83A,1,13.018,436099.496,27255.301,27255.679,16223714603174144.000,127372346.305,-15532429684940.145
156,84X,1,17.298,100593887.822,919328.247,919328.486,107667509019547484160.000,10376295534.513,-18356087810872084.000
220,51D,2,20.156,3722.140,-53.015,53.189,137094606591.351,370262.888,-21671986.582
241,40E,1,7.337,734288.123,36713.947,36714.236,2443508537638652.500,49431857.518,-2181649979919.351
248,16D,1,18.307,1709833030.097,-17627144.585,17627144.785,5244810893665171931136.000,72421066642.692,-2517501282304750080.000
250,41D,1,15.572,30533931171.529,213727605.975,213727606.406,90901292795533310558208.000,301498412592.062,-73007332804014751744.000

In [8]:
good = Lin_Reg[Lin_Reg['Mean_Absolute_Error_Test']< 1000]

In [22]:
good.describe()

,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
count,243.000,243.000,243.000,243.000,243.000,243.000,243.000,243.000
mean,1.514,14.784,14.848,-0.113,0.290,615.857,23.675,0.703
std,0.501,4.653,4.673,0.038,0.058,486.011,7.454,0.081
min,1.000,6.890,6.616,-0.357,0.156,110.178,10.497,0.469
25%,1.000,12.037,12.061,-0.128,0.255,383.079,19.572,0.645
50%,2.000,14.332,14.407,-0.109,0.289,496.874,22.291,0.699
75%,2.000,16.335,16.411,-0.091,0.316,680.842,26.093,0.751
max,2.000,45.271,45.047,-0.043,0.628,4915.039,70.107,0.901

In [17]:
good.describe().to_csv('results_compared.csv', index=False, header=True , mode='a')

# Decision Tree

In [11]:
Dec_tree[Dec_tree['Route'] == '83A']

,Route,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
136,83A,1,13.658,14.153,-0.127,0.303,416.518,20.409,0.601
137,83A,2,12.242,12.837,-0.126,0.293,381.969,19.544,0.674

In [20]:
Dec_tree.describe()

,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
count,252.000,252.000,252.000,252.000,252.000,252.000,252.000,252.000
mean,1.504,14.569,15.606,-0.140,0.309,674.631,24.828,0.672
std,0.501,4.158,4.629,0.051,0.067,516.177,7.644,0.094
min,1.000,6.521,7.104,-0.405,0.160,124.255,11.147,0.310
25%,1.000,12.124,12.928,-0.165,0.263,436.198,20.885,0.604
50%,2.000,14.438,15.178,-0.135,0.307,562.376,23.714,0.672
75%,2.000,16.111,17.024,-0.108,0.345,745.086,27.296,0.730
max,2.000,41.690,46.578,-0.043,0.576,5493.565,74.119,0.903

In [18]:
Dec_tree.describe().to_csv('results_compared.csv', index=False, header=True , mode='a')

# Random Forest

In [14]:
Random_Forest

,Route,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
0,68,1,8.960,9.620,-0.097,0.227,263.246,16.225,0.775
1,68,2,10.131,10.860,-0.112,0.246,355.674,18.859,0.685
2,25B,1,12.096,13.253,-0.089,0.226,429.826,20.732,0.811
3,25B,2,13.661,14.865,-0.101,0.240,596.506,24.423,0.712
4,45A,1,8.920,9.748,-0.072,0.204,239.252,15.468,0.744
...,...,...,...,...,...,...,...,...,...
249,77X,2,13.655,16.398,-0.123,0.261,753.679,27.453,0.778
250,16D,1,15.007,18.943,-0.140,0.330,819.099,28.620,0.607
251,33E,1,10.158,12.551,-0.169,0.308,350.664,18.726,0.555
252,41D,1,14.139,18.132,-0.112,0.337,736.603,27.140,0.408
253,41D,2,15.923,18.055,-0.214,0.377,671.183,25.907,0.768

In [21]:
Random_Forest.describe()

,Direction,Mean_Absolute_Error_Train,Mean_Absolute_Error_Test,Mean_Percentage_Error,Mean_Absolute_Percentage_Error,Mean_Squared_Error,Root_Mean_Squared_Error,R_Square
count,252.000,252.000,252.000,252.000,252.000,252.000,252.000,252.000
mean,1.508,11.872,13.783,-0.111,0.258,558.412,22.532,0.731
std,0.501,3.488,4.377,0.037,0.051,445.859,7.135,0.078
min,1.000,5.516,6.590,-0.353,0.147,111.497,10.559,0.408
25%,1.000,9.599,11.061,-0.127,0.225,345.209,18.580,0.680
50%,2.000,11.532,13.208,-0.110,0.256,442.238,21.029,0.729
75%,2.000,13.536,15.402,-0.089,0.284,630.756,25.115,0.781
max,2.000,34.765,43.839,-0.044,0.487,4894.188,69.958,0.918

In [19]:
Random_Forest.describe().to_csv('results_compared.csv', index=False, header=True , mode='a')